# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://oleskiewicz.github.io/aoc2020/"

git_url = "https://github.com/oleskiewicz/aoc2020/tree/master/"

def custom_doc_links(name): return None
