# AUTOGENERATED! DO NOT EDIT! File to edit: 09.ipynb (unless otherwise specified).

__all__ = ['window', 'pairwise', 'split']

# Cell
def window(iterable, size=1):
    for i in range(0, len(iterable) - size + 1):
        yield tuple(iterable[i:i + size]) if size > 1 else iterable[i]

# Cell
def pairwise(xs):
    return zip(xs, xs[1:])

# Cell
def split(xs, at):
    return [list(group) for k, group in groupby(xs, lambda x: x == at) if not k]