# AUTOGENERATED! DO NOT EDIT! File to edit: 09.ipynb (unless otherwise specified).

__all__ = ['window']

# Cell
def window(iterable, size=1):
    for i in range(0, len(iterable) - size + 1):
        yield tuple(iterable[i:i + size]) if size > 1 else iterable[i]